name: Format Markdown and Push to Site Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # needed for pushing formatted changes

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier on Markdown
        run: prettier --write "**/*.md"

      - name: Rename Markdown files (spaces → dashes, skip README)
        run: |
          find . -type f -name "*.md" ! -path "./templates/*" | while read -r file; do
            base=$(basename "$file")
            dir=$(dirname "$file")
            if [ "$base" = "README.md" ]; then
              continue
            fi
            newbase=$(echo "$base" | tr '[:upper:]' '[:lower:]' | sed -E 's/[ ]+/-/g')
            if [ "$base" != "$newbase" ]; then
              git mv "$file" "$dir/$newbase"
            fi
          done

      - name: Fix Obsidian-style links after renaming
        run: |
          find . -type f -name "*.md" ! -path "./templates/*" | while read -r file; do
            sed -E -i '
              s/\[([^\]]+)\]\(([^\)]+)[ ]+([^\)]+)\.md\)/[\1](\L\2-\3.md)/g;
              s/\[([^\]]+)\]\(([^\)]+)[ ]+([^\)]+)[ ]+([^\)]+)\.md\)/[\1](\L\2-\3-\4.md)/g;
            ' "$file"
          done

      - name: Add full-path Markdown links next to Hugo ref links (no duplicates)
        run: |
          find . -type f -name "*.md" ! -path "./templates/*" | while read -r file; do
            awk '
              # Case 1: Skip commented Hugo refs
              /^<!--.*\{\{< ref .*\.md >\}\}.*-->$/ { print; next }

              # Case 2: Hugo ref link that already has a plain .md link → leave unchanged
              /\]\(\{\{< ref "[^"]+\.md" >\}\}\).*]\([^ ]+\.md\)/ { print; next }

              # Case 3: Hugo ref link without a trailing .md link → add one
              /\[[^]]+\]\(\{\{< ref "[^"]+\.md" >\}\}\)/ {
                gsub(/\[([^\]]+)\]\(\{\{< ref "([^"]+\.md)" >\}\}\)/,
                     "[\\1]({{< ref \"\\2\" >}}) - [\\1](\\2)")
                print; next
              }

              # Default: print line unchanged
              { print }
            ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done

      - name: Commit formatted changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: format markdown, rename files, fix links"

      - name: Push to site repo (Generate GitHub App token)
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_retrieval_mode: repository
          installation_retrieval_payload: matt2ology/matt2ology.github.io

      - name: Push changes
        run: git push https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/matt2ology/matt2ology.github.io main
